### ISSUE TITLE
[feat] 활동보고 페이지 UI 구현 

### ISSUE THREAD

**Issue by si14444** [DEPthes/MJU-Council-Web#1]
## 🌏Summary
>  활동보고 페이지 UI 구현

## ✔️ Task & Description
- [x] 정책목록 페이지 UI
- [x] 사업목록 페이지 UI
- [x] 사업목록 상세 페이지 UI
- [x] 사업목록 검색 결과 페이지 UI
- [x] 제휴 현황 페이지 UI
- [x] 제휴 현황 상세 페이지 UI

## 🐸 Reference
-
