### ISSUE TITLE
[Feat] 공지사항 UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPthes/MJU-Council-Web#11]
## 🌏 Summary
>  공지사항 UI 제작

## ✔️ Task & Description
- [x] 공지사항 페이지
- [x] 공지사항 검색 결과 페이지
- [x] 공지사항 검색 결과 페이지 Empty
- [x] 공지사항 상세 페이지
- [x] 행사 페이지
- [x] 행사 안내 모음 페이지
- [x] 행사 안내 상세 페이지

## 🐸 Reference
-
