### ISSUE TITLE
feat/#2-메인페이지 UI 구현

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#2]
## 🌏Summary
>  메인페이지 UI 구현

## ✔️ Task & Description
- [x] Navbar component 구현
- [x] Banner component layout 구현
- [x] Banner component slide 구현
- [x] HomePageBtn component 구현 (banner 위 버튼)
- [x] HomeCategory component 구현
- [x] HomeNotice component 구현 (메인페이지 공지사항)
- [x] Footer component 구현

## 🐸 Reference
-
