### ISSUE TITLE
[Feat] 자료집 UI 제작

### ISSUE THREAD

**Issue by rlotr02** [DEPthes/MJU-Council-Web#20]
## 🌏 Summary
>  자료집 UI 제작

## ✔️ Task & Description
- [x] 회의록 리스트 UI 제작
- [x] 회의록 리스트 검색결과 UI 제작
- [x] 회의록 상세 페이지 UI 제작
- [x] 회칙 및 세칙 리스트 UI 제작
- [x] 회칙 및 세칙 상세 페이지 UI 제작

## 🐸 Reference
-
