### ISSUE TITLE
[feat] 총학생회 소개 UI 구현

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#26]
## 🌏 Summary
>  총학생회 소개 페이지 구현

## ✔️ Task & Description
- [x] introduce banner component 생성
- [x] 소개, 조직도, 국별업무소개, 중앙운영위원회 버튼 component 생성
- [x] 소개 component
- [x] 조직도 component
- [x] 국별 업무 소개 component
- [x] 중앙운영위원회 component
- [x] 학생자치기구 component
- [x] 페이지 라우팅

## 🐸 Reference
-
