### ISSUE TITLE
[fix] 메인페이지 banner, router 수정

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#30]
## 🌏 Summary
>  메인페이지 banner 사진 로드 및 router 연결, menubar 수정

## ✔️ Task & Description
- [x] 페이지 routing
- [x] banner 사진 로드
- [x] insta, kakao 버튼 연결
- [ ] menubar 위치 수정

## 🐸 Reference
-
