### ISSUE TITLE
[fix] 사진 로드 오류, QA 기반 수정

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#37]
## 🌏 Summary
>  QA기반 수정

## ✔️ Task & Description
- [ ] footer 전화번호 수정
- [ ] footer copyright 수정
- [ ] navbar-로고 누르면 홈으로 라우팅(메뉴바 state도 false로 바꾸기)
- [ ] 조직도, 국별 업무 이미지 위 margin값 수정
- [ ] banner 이미지 로드 svgr 기반 수정
- [ ] 소개 페이지 이미지 svgr 기반 수정
- [ ] 메인페이지 카테고리 max-width에 따라 비율 조정(css 수정)

## 🐸 Reference
- svg 파일 수정하기
- preserveAspectRatio="xMidYMid slice" 부모의 크기에 맞게 조정되도록 / width랑 height 지우기
