### ISSUE TITLE
[Feat] 공지사항 API 연동

### ISSUE THREAD

**Issue by rlotr02** [DEPthes/MJU-Council-Web#39]
## 🌏 Summary
>  공지사항 API 연동

## ✔️ Task & Description
- [x] 공지사항 목록 조회
- [x] 공지사항 상세 조회
- [x] 행사 목록 조회
- [x] 행사 상세 조회
- [x] 행사 세부사항 상세 조회
