### ISSUE TITLE
[Feat] 메인페이지 api 연동

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#44]
## 🌏 Summary
>  메인페이지 api 연동

## ✔️ Task & Description
- [x] banner api 연동
- [x] 공지사항 api 연동
- [ ] footer api 연동

## 🐸 Reference
-
