### ISSUE TITLE
[Feat] 소개페이지 api 연동

### ISSUE THREAD

**Issue by kimssoyeon** [DEPthes/MJU-Council-Web#47]
## 🌏 Summary
>  소개페이지 api 연동

## ✔️ Task & Description
- [x] 소개부분 api 연동
- [x] 중앙운영위원회 api 연동
- [x] 조직도 api 연동
- [x] 국별업무소개 api 연동
- [x] css 오타 수정
- [x] prop warning 수정

## 🐸 Reference
-
